[project]
authors = ["Jeremy Tuloup <jeremy.tuloup@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "lite-previews"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pip = ">=24.3.1,<25"
python = ">=3.12.8,<3.13"
jupyterlab = "4.3.*"
nodejs = "22.*"
hatch = "*"
ruff = ">=0.8.6,<0.9"
