name: Build JupyterLite Preview

on:
  workflow_dispatch:
    inputs:
      jupyterlab_pr:
        description: 'JupyterLab PR URL'
        required: false
        type: string
      notebook_pr:
        description: 'Notebook PR URL'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lite-previews
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Clone JupyterLab
        run: |
          gh repo clone jupyterlab/jupyterlab
          if [ -n "${{ github.event.inputs.jupyterlab_pr }}" ]; then
            PR_NUM=$(echo "${{ github.event.inputs.jupyterlab_pr }}" | grep -oE '[0-9]+$')
            cd jupyterlab
            gh pr checkout $PR_NUM
          fi

      - name: Clone Notebook
        run: |
          gh repo clone jupyter/notebook
          if [ -n "${{ github.event.inputs.notebook_pr }}" ]; then
            PR_NUM=$(echo "${{ github.event.inputs.notebook_pr }}" | grep -oE '[0-9]+$')
            cd notebook
            gh pr checkout $PR_NUM
          fi

      - name: Clone JupyterLite
        run: git clone https://github.com/jupyterlite/jupyterlite.git

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch

      - name: Build JupyterLite
        run: python build.py

      - name: Create JupyterLite site
        run: |
          python -m pip install jupyterlite/py/jupyterlite-core/dist/*.whl
          mkdir site
          cd site
          jupyter lite init
          jupyter lite build

      - name: Upload site artifact
        uses: actions/upload-artifact@v3
        with:
          name: jupyterlite-site
          path: site/_output